name: flutter_monthly_calendar
description: Monthly Calendar for Flutter.
version: 0.0.1
homepage: https://github.com/ChangJoo-Park/flutter_monthly_calendar
repository: https://github.com/ChangJoo-Park/flutter_monthly_calendar

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  expandable_page_view: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  benchmark_harness: ^2.0.0
  lints: ^1.0.1

flutter: null